name = "BacteriaAbsNorm"
uuid = "69687de0-4b22-4042-8423-6b077f3bf3ca"
authors = ["Nick Owens <owensnick@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
